create table user
(
    id          integer generated by default as identity,
    user_id     varchar(40)  not null,
    user_name   varchar(100) not null,
    password   varchar(100) not null,
    create_time timestamp    not null default current_timestamp,
    PRIMARY KEY (id)
);
create table role
(
    id          integer generated by default as identity,
    role_id     int  not null,
    role_name   varchar(100) not null,
    create_time timestamp    not null default current_timestamp,
    PRIMARY KEY (id)
);
create table resource
(
    id          integer generated by default as identity,
    resource_id     int  not null,
    resource_name   varchar(100) not null,
    resource_path   varchar(200) not null,
    resource_type   int not null default 0,
    create_time timestamp    not null default current_timestamp,
    PRIMARY KEY (id)
);
create table user_role
(
    id          integer generated by default as identity,
    role_id     int  not null,
    user_id     varchar(40)  not null,
    create_time timestamp    not null default current_timestamp,
    PRIMARY KEY (id)
);
create table resource_role
(
    id          integer generated by default as identity,
    role_id     int  not null,
    resource_id     int  not null,
    create_time timestamp    not null default current_timestamp,
    PRIMARY KEY (id)
);
